### ISSUE TITLE
Maribel's Portfolio Site: (link inside)

### ISSUE THREAD

**Issue by outdoorsole** [soggybag/Front-end-Web-Class-8#11]
Github repo: https://github.com/outdoorsole/portfolio
live site: http://maribelmontejano.com/

**Comment by Nkdream** [comment]
Your website looks very professional and organized. The only thing i noticed is that the contact info seems a little small in the footer. I think you could make those icons bigger.

**Comment by Hassurunous** [comment]
Good: The "window" to the background on the RWE quote, the UI design, and the color palette are great!
Better: The "contact" section appears to be missing, but I'm sure that's in development!
Best: I love the way the website flows from the introduction, to the timeline, into the skills, portfolio and the contact information. Great design!

**Comment by Nicholas-Swift** [comment]
Good:
- A lot of content on the site!
- Really like the color scheme.
- Navbars <3

Better:
- I don't think the arrow to scroll to the top is needed, it just adds more complexity to the site when you don't need to have it. The user can just use the navbar.
- I feel like it would look nicer if the footer had more height. and was maybe a little darker. You could integrate the social div (twitter, github, linked in) into the footer.
- The portfolio section could look better if you had the projects/products inside their respective platforms. An app would be in an iphone frame, a website/desktop app would be in a computer, etc.

Best:
- I love the logo of your name. REALLY nice.

**Comment by Saturn-V** [comment]
Good:
- Good amount of information
- Consistent
- Timeline

Better: 
- If you are going to use the arrow to take me back to the top, make it larger so that people can notice it's there. EMBRACE THE BUTTON.
- Make the footer all the same color, or just make the color change a little more subtle so that it looks like one whole footer and not two separate sections.
- I noticed some lag when initially loading the page, you may want to check that out.
- Try to frame your projects a little better. The website is very professional, but when I see your projects, it looks kinda crammed in a window.

Best:
- I really like the look and feel.
- The timeline is dope, I can see what you've done over the years.
- Project section is dope, you should inclde a caption for each one.
- Nice color scheme. :]

**Comment by soggybag** [comment]
This looks really good. I feel your site would benefit from some vertical space. Give everything some margin in the top and bottom. 

With the about text and your image at the top I might consider placing these side by side. You have a lot of text here and center aligned is not easy to read. 

I like your font styles. 

Think about adding some more space between the text in the experience boxes and the edge of the box. 

I like the red circle with the dates. You could make the circle larger to give the text a little more space.
