### ISSUE TITLE
www.nickdreamdev.com

### ISSUE THREAD

**Issue by Nkdream** [soggybag/Front-end-Web-Class-8#14]

**Comment by Nicholas-Swift** [comment]
Good:
- A lot of content, that's good. I also like the site logo.

Better:
- I feel like the current font is a little too small.
- The search feature probably isn't needed unless a LOT more content is added. The website might look better as just a one page site.
- The green on the buttons doesn't feel quite in place. It might be better to have it be a different color.
- When you scroll down, the nav bar pops to the top rather than shifting to the top or sticking once you scroll down.
- You have links to your twitter and email in your about section, but it might be better to have images that link to those.

Best:
- There's a lot of content on the site!

**Comment by alexander-dejeu** [comment]
I agree with a lot of what Swift has already mentioned, especially the point about the font being very small.  Overall, great content.  Definitely should consider making it easier to find your "about me" section.  It would also be nice if on your about me section there were links to your different handles.  Great start - excited to see where this site goes

**Comment by nehemiah-io** [comment]
Decent writing and nice about you page

Font is to tiny on the page even though you are so descriptive

The workout picture is hilarious

**Comment by 2bithack** [comment]
great work. love the layout and the content. would agree with swift and say that the text should be a little larger. i like the liberal use of links tho. can't wait to see this page as it developes.

**Comment by brianhans** [comment]
I like how your site has a lot of content. I would center the information and remove the left navbar and top navbar altogether. I would also add your name somewhere on the page along with contact information. Making the font size a little bigger may also help with readability. The about me page should be above the blog posts though because I missed that when I first visited the website. It is a good base and a couple of minor changes could make it even better.

**Comment by nonafiona** [comment]
Your site has a clear intention through its design - to share your experiences & products that you create. It has a lot of content & clear layout but could use a little bit of redistribution of space. It might help to use grid layout, but besides that, I love it. Great work 👌🏼

**Comment by soggybag** [comment]
Can't find the link to your site?
