### ISSUE TITLE
www.davidkc.com

### ISSUE THREAD

**Issue by davidkc0** [soggybag/Front-end-Web-Class-8#15]
www.davidkc.com 

simple and elegant.

**Comment by alexander-dejeu** [comment]
As promised - clean and elegant.

Looking forward to the structure of the blog + portfolio.

One thing to consider is how you bold/unbold the back button for when you navigate to a different page on your website.  Maybe just have it go to bold if you go to the back button

**Comment by 2bithack** [comment]
loved the use of colors and the contact hover over animations with "your" stars. pretty sick. i like the centering and spacing in the typography. can't wait to see it with content and hope to see more of the sweet colors and animations.

**Comment by outdoorsole** [comment]
Hi David!

Feedback:
- I like how the fonts and colors that you chose for your name look against the white background of the site. It looks professional.
- The back button feature is a really nice addition, yet may not be intuitive at first for people to find (since you have to hover over content for it to appear). Once the content is in place, it might be easier to figure out how to customize the navigation.

I would be happy to revisit your site and provide more feedback once more content is added. Keep up the good work!

**Comment by Nkdream** [comment]
This a rails app. not a website. please only post websites. flagged and reported

**Comment by nonafiona** [comment]
d a v i d - 
your font styling (for your name) is 👌🏼
one thing I might improve - your icon shape edges could be cleaned up. overall, I love the :hover animation. 
your site is simple & appealing, I can't wait for the blog portion.

**Comment by soggybag** [comment]
This is looking really good so far. I like the hover, here is a suggestion, why not use one class that is shared across all of the letters with the transition. This would let you set the transition in one place. Which would make it easier to change the time. 

`.letter { transition: 400ms; }`

I noticed you used the center tag. This is deprecated. You should use text-align center, or set the width of the block and margin:auto. 

here is a complete guide to centering things with CSS: https://css-tricks.com/centering-css-complete-guide/
