### ISSUE TITLE
https://coreyarch1234.github.io/

### ISSUE THREAD

**Issue by coreyarch1234** [soggybag/Front-end-Web-Class-8#2]
Take a look and give some feedback.

**Comment by juanpablofernandez** [comment]
I like your website however you could add/fix a few things: 
- Maybe you could add the front part of an arrow facing down in the first page, so that people know they can scroll down?
- Go easier on the colors, I feel like there are to many cluttered together on the bottom part of the site
- Get rid of the html or body margin, so that the bottom part of your site fits fills the width (there's a tiny bit of margin)
- Maybe move the CoffeAlum label at the top a bit to the right

**Comment by outdoorsole** [comment]
Hi Corey!

Feedback:
- The title of "CoffeeAlum" appears to be at the top left corner on my screen. I think if padding is added on the left of the Title text, it would bring the title into full view (the "C" in CoffeeAlum is cut off on my screen).
- I like the color scheme that you are using! The white text is a little hard to see against the tan, so I would try darkening the shade just a bit so that there is more contrast.

Good job Corey!

**Comment by Nkdream** [comment]
The content itself is good, but I feel as though the design could use some work, for instance I feel like the colors do not synergize very well. Some of the elements on the page are not aligned exactly and a tiny bit off center. It is a small detail but I feel as though it would make a huge difference

**Comment by davidkc0** [comment]
Very simple and elegant! The few changes I would make are: 
1. keep the font color the same. in the orange box you have black font but for the rest of the site you have white. 
2. The site has a side scrolling issue. Make sure it fits the page. 
3. Add a logo to the header. I understand this is a new idea, so you might not have a logo yet, but when you do make sure to make it the enter point of your header section.
4. Add "Made with ♥ in San Francisco, CA" to the footer. All the cool hipster startups do it. ;)

**Comment by tlambrou** [comment]
Nice job Corey! I really like the colors and the big prominent text.  
- One thing I should point out is that the flow of the content gets pretty wonky if you resize the window.
- The tan color in the lower right doesn't seem to go as well with the yellow in the palette as well.  I would suggest trying coolors.co to find another color that works best with that palette.

**Comment by brianhans** [comment]
I like the simple design and color scheme. I would center the content on the main screen though and remove the margin on the body so that the blocks extend to the edge of the screen. The bars get misplaced when the screen gets too small. I'm gonna try to make a pull request with some of my suggested edits later today so you can see if you like the changes.
