### ISSUE TITLE
https://auxmusic.io

### ISSUE THREAD

**Issue by thanasistratigakis** [soggybag/Front-end-Web-Class-8#3]

**Comment by kojino** [comment]
Good:
The basic layout is perfect for showcasing your app. Big enough screenshots with good explanations of features. It's awesome that you have an app on app store that can have a landing page like this. The logo is cool.

Better:
Maybe you should change the background of the top div?  In general, the styling is cool, but it is too calm, in my opinion. I want more excitement in the color scheme! Also, as a user, it is hard to see at a glance why I should use this app. People don't read texts, so have a very very short description of one feature that I should know.

Best:
This is a great MVP for the landing page tho. It has all the foundation ready for further improvements. Nice work!!!

**Comment by juanpablofernandez** [comment]
I feel like the whole website is good overall, very elegant and fits the app perfectly.

However I feel that some animations might make it nicer, maybe when you hover over certain buttons they can become bigger or jump a bit.

**Comment by davidkc0** [comment]
Very elegant and simple! There would only be a few alternations I would make. 
1. Change the font. Its too basic. Maybe Lato would be a better choice?  
2. Change the footer color, and decrease the height. Its too black, and it seems out of place. Try inverting the colors. Another suggestion would be to have the header and footer colors match. Keep the colors friendly and inviting. (https://blog.kissmetrics.com/psychology-of-color-and-conversions/) 
3. Another idea would be to have a background image for the header instead of a solid color. The more arbitrary and unrelated the image is to what aux actually does the better. 
4. Add "Made with ♥ in San Francisco, CA" to the footer. All the cool hipster startups to it.

**Comment by coreyarch1234** [comment]
Good: The simple color scheme (black and white) adds an appropriate modern feel to the site.

Better: It seems to have too much text. I can see how each point (live radio, social, discover) are all key in delivering the message, but it is too much to read for people who simply skim sites. It is rare for people to actually take the time to absorb all of the information.

My solution is to make the amount of text seem less by aligning the text horizontally. When people read from left to right, it feels much more natural. If it feels more natural, people will read much more quickly and feel as if the text is not as overwhelming.

Best: The screen shots of the iPhone with the app running is key to describing what the point of the app is.

**Comment by soggybag** [comment]
Looks great, good job! I feel this could still be improved with some effort.

The sections alternate between light and dark gray. These are nice colors but as the only colors the site gets monotonous. Think about using a color for the Seamless sharing, and in Beta sections.
