### ISSUE TITLE
https://github.com/kojino/kojinoshiba.com

### ISSUE THREAD

**Issue by kojino** [soggybag/Front-end-Web-Class-8#4]
https://github.com/kojino/kojinoshiba.com

**Comment by juanpablofernandez** [comment]
Your site's layout looks very professional, I like it however there are a few things you could improve:
- Your initial image (You're photo) flickers a bit when hovering over it.
- On the Software Engineering tab, the CoffeAlum image doesn't cover the whole rectangle
- On the Software Engineering tab, the Hikakaku description when you hover over it could have a margin so that it doesn't look so crammed.
- On the Machine Learning Tab, the descriptions should be smaller so that they fit within the circles.
- On the Education Tab, it feels a bit weird hovering over the divs, Maybe the whole rectangle could be highlighted instead of just the left part?
- Also: You could have a darker background when hovering over the different divs, sometimes you can't read the text correctly

Good work over all!

**Comment by samlee405** [comment]
I love the initial screen and the interactivity of your photo. It also gives all the information you really need at a quick glance. I also like that your portfolio highlights your interests and skills across a variety of areas. It does well to showcase the various talents you have.

I feel that the lower screens can benefit from a bit more text and description that can be seen without having to hover over each project. Maybe like a quick, one sentence description over the top of each section. It would also be great to have the hover over text be a bit more responsive (lower the transition time). Lastly, I think it would be good to stick to a single theme for each section. Specifically, you switch between boxes and circles to enclose your projects and I think it would be better to stick to one or the other. Though that might be just be my personal taste showing.

**Comment by davidkc0** [comment]
I like the color scheme, but the website is too "busy" for lack of a better term. for the 3 different sections of your site, keep the buttons and layout the same. Having 3 different layouts is a bit distracting and disorienting. I would also suggest that all 3 sections have the same background color. Remember simple and elegant.

**Comment by brianhans** [comment]
The overall site is really cool. I would change the color of the column on the left to make it stand out more. The layout on the right is really nice, I would recommend getting higher resolution photos for some of the Gradel logo and some of the other images that look blurry. I would also make the images fill the entire box in the second section, as some do and others don't. The images should as be centered in the circles in my opinion and maybe try spacing them out a little more. The site looks really well done and give a lot of information about you.

**Comment by soggybag** [comment]
Great work, I really like what you have made. Don't stop here! I feel this could improve with work! Here are some suggestions for things to look at. 

The links could use a hover style, and a selected state. I covered this in class, ask me if you have any questions. 

Think about the layout of elements. The circles in the machine learning section are too close together on the vertical axis. soaking these with geometric precision will reinforce the subject message.
