### ISSUE TITLE
https://github.com/ChandanB/My-Site

### ISSUE THREAD

**Issue by ChandanB** [soggybag/Front-end-Web-Class-8#6]
https://github.com/ChandanB/My-Site

**Comment by brianhans** [comment]
I like the design is simple and to the point. The dark background works and the contrast between the boxes with borders and the filled ones is a cool effect. There isn't any space to show off your projects, which potential employers will probably want to see, so I would add that. You could keep the current layout and just add maybe a large box with an outline that you can see just the top of it with one of your projects inside of it.  LinkedIn is also the only text that doesn't start with a capital letter.

**Comment by kojino** [comment]
I love websites that I don't have to scroll. It's compact and concise. On the other hand, I also felt that I want to know more about you, especially what you've made so far. Try to add more content, but keep the conciseness stay there because I think it's great.
As for the styling, change the social media buttons with their icons. It will be more intuitive for the visitors to understand where the link leads us to.
Keep working and let me know if you made more progress!!

**Comment by Casey-S** [comment]
Compact. Precise. Minimal. Easy to read. At least three of these things describe this website. Call me Ronald McDonald cuz I'm lovin' it. Only criticism is the colors are a bit harsh (Going full #000 is a bit too harsh of a black), just soften the background a bit imo.

**Comment by soggybag** [comment]
This looks really good. I like your work. I really like this font styles you have used. This can still be improved with work! 

Align center works well for the headings, but is not work as well for about paragraph. Think about using: text-align: justify here. 

Your button/links need a hover style. This will make the site feel active and interesting. It will also clue people that they can click these.
