### ISSUE TITLE
https://github.com/Hassurunous/hassurunous.github.io

### ISSUE THREAD

**Issue by Hassurunous** [soggybag/Front-end-Web-Class-8#7]

**Comment by twof** [comment]
It looks like you have a great framework set up with spaces for all the content you want to add in later. That'll make design much easier as you go on. The nav bar is all scrambled, and I'm not sure if that's intentional or not.

You could use some more spacing in between sections because right now it feels claustrophobic. I wouldn't do two columns of text especially if it's going to be long because if someone wants to read one column after reading the other, they have to scroll back up the page. 

I'd reccomend blurring out the background. I like that you added the darker overlay to make text more readable. That was a good call. However it still feels a little cluttered.

**Comment by brianhans** [comment]
The site has a rustic/nature look which is unique compared to most of the other portfolio sites that I've seen. It seems like there are some layout with the top nav bar and with the text at the top:
![image](https://cloud.githubusercontent.com/assets/7691482/19571709/e109999e-96b3-11e6-8700-d134279eb232.png) 
It seems like you have several distinct sections and I would make them more apparent with some sort of line between them. The semi-transparent background makes the text difficult to read, but also contributes to the style so like Alex said maybe try doing a blur. There is a css blur effect, I haven't used it, but you should try it out (filter: blur(5px))

**Comment by kojino** [comment]
Great start with the basic frames ready. First thing I would do from here is to create a paper prototype of how the portfolio would look like. Then move on to choosing the color scheme for the site. When designing portfolio websites, there are a lot of things you should do before you start coding, and it should be much easier for you to focus when you actually start coding.

Having said that, few tips when creating the paper prototype would be:
1. Don't fill the entire page with texts. Make the texts concise and try to add more images.
2. Spend more time choosing your image. Dig into your facebook photos and find high resolution ones!

Good luck with your future work and let me know when you made some progress!

**Comment by thanasistratigakis** [comment]
Hard to give feedback without all the content.  But my first suggestion is that you don't replace all that lorum ipsum text with more text.  Even full sentences may be a bad idea.  Try to communicate everything will bullet points, images, and links to full projects. 
Everything else that I would suggest is already listed above ^^^^

**Comment by soggybag** [comment]
Looks good, great start, this can still be improved with work. The links at the top are working well but need some more space. Think about adding some space above and below the links. 

Look closely at the type styles. You could create a wider variety of styles. Using another color or font family would make the heading stand out.
